name: Gnuine lab
description: Un blog de desarrollo web Ruby on Rails
url: http://lab.gnuine.com
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "page:num"
analytics:
  provider: google
  google: 
    tracking_id: 'UA-50358422-1'